# Generated by Django 2.2.15 on 2020-12-25 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Departamentin adı')),
            ],
            options={
                'verbose_name_plural': 'Departamentlər',
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Müraciət səbəbi')),
            ],
            options={
                'verbose_name_plural': 'Müraciət səbəbləri',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_created_date', models.DateTimeField(blank=True, null=True, verbose_name='Müraciət tarixi')),
                ('task_completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Müraciətin icra tarixi')),
                ('task_status', models.CharField(choices=[('İmtina edilib', 'İmtina edilib'), ('Gözləmədədir', 'Gözləmədədir'), ('İcra edilib', 'İcra edilib')], default='Gözləmədədir', max_length=30, verbose_name='Müraciətin statusu')),
                ('task_content', models.CharField(blank=True, max_length=200, null=True, verbose_name='Müraciətin məzmunu')),
                ('client_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Müraciət edən işçi')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Müraciətin icrası haqqında məlumat')),
                ('client_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk_app.Department')),
                ('task_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk_app.Reason')),
            ],
        ),
    ]
