# Generated by Django 2.2.15 on 2020-12-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'Tapşırıqlar'},
        ),
    ]
