# Generated by Django 2.2.15 on 2020-12-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0002_auto_20201225_0440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Departament', 'verbose_name_plural': 'Departamentlər'},
        ),
        migrations.AlterModelOptions(
            name='reason',
            options={'verbose_name': 'Müraciət səbəbi', 'verbose_name_plural': 'Müraciət səbəbləri'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tapşırıq', 'verbose_name_plural': 'Tapşırıqlar'},
        ),
    ]
