# Generated by Django 2.2.15 on 2020-12-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0003_auto_20201225_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_content',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Müraciətin məzmunu'),
        ),
    ]
