# Generated by Django 2.2.15 on 2020-12-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0006_auto_20201225_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Müraciətin icrası haqqında məlumat'),
        ),
    ]
