# Generated by Django 2.2.15 on 2020-12-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Aytişniklər'},
        ),
    ]
