# Generated by Django 2.2.15 on 2020-12-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_auto_20201225_0403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Aytişnik', 'verbose_name_plural': 'Aytişniklər'},
        ),
    ]
